import Phaser from "phaser";
import { Room } from "colyseus.js";
type ArenaSceneData = {
    room?: Room;
};
export declare class ArenaScene extends Phaser.Scene {
    private room?;
    init(data: ArenaSceneData): void;
    private netPlayers;
    private remoteTargets;
    private readonly remoteLerpSpeed;
    private remotePlayers;
    private remoteFacingIndicators;
    private remoteSwordHitboxes;
    private lastSentX;
    private lastSentY;
    private lastSentFacingAngle;
    private playerHpText;
    private enemyHpText;
    private roundBannerText;
    private readonly localPlayerColor;
    private readonly remotePlayerColor;
    private readonly playerHitColor;
    private readonly playerFlashColor;
    private readonly invincibilityFlashFrequency;
    private readonly facingIndicatorLength;
    private readonly swordSwingArc;
    private player;
    private wKey;
    private aKey;
    private sKey;
    private dKey;
    private spaceKey;
    private readonly gameWidth;
    private readonly gameHeight;
    private readonly wallThickness;
    private readonly playerSize;
    private readonly playerSpeed;
    private readonly dashSpeed;
    private readonly dashDuration;
    private readonly dashCooldown;
    private isDashing;
    private dashTimeRemaining;
    private dashCooldownRemaining;
    private dashDirection;
    private facingIndicator;
    private facingAngle;
    private swordHitbox;
    private readonly swordLength;
    private readonly swordWidth;
    private readonly swordDistance;
    private readonly attackDuration;
    private readonly attackCooldown;
    private attackAimAngle;
    private isAttacking;
    private attackTimeRemaining;
    private attackCooldownRemaining;
    constructor();
    create(): void;
    update(_time: number, delta: number): void;
    private getMoveDirection;
    private updateDashState;
    private movePlayer;
    private clampPlayerToArena;
    private checkForDashInput;
    private startDash;
    private updateFacingAngle;
    private drawFacingIndicator;
    private createSwordHitbox;
    private startSwordAttack;
    private handleSwordInput;
    private updateSwordState;
    private bindRoomState;
    private syncMovementToServer;
    private cleanupNetwork;
    private updateRemotePlayerSmoothing;
    private drawFacingLine;
    private getSwordSwingAngle;
    private setSwordVisual;
    private updateRemoteFacingAndSwordVisuals;
    private updatePlayerHitVisuals;
}
export {};
